// megafunction wizard: %ROM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: ROMifetch.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 9.0 Build 132 02/25/2009 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2009 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altsyncram CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone II" ENABLE_RUNTIME_MOD="NO" INIT_FILE="all_prog_instructions.mif" NUMWORDS_A=1024 OPERATION_MODE="ROM" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="UNREGISTERED" WIDTH_A=32 WIDTH_BYTEENA_A=1 WIDTHAD_A=10 address_a clock0 q_a
//VERSION_BEGIN 9.0 cbx_altsyncram 2008:11:06:10:05:41:SJ cbx_cycloneii 2008:05:19:10:57:37:SJ cbx_lpm_add_sub 2008:12:09:22:11:50:SJ cbx_lpm_compare 2009:02:03:01:43:16:SJ cbx_lpm_decode 2008:05:19:10:39:27:SJ cbx_lpm_mux 2008:05:19:10:30:36:SJ cbx_mgl 2009:01:29:16:12:07:SJ cbx_stratix 2008:09:18:16:08:35:SJ cbx_stratixii 2008:11:14:16:08:42:SJ cbx_stratixiii 2008:12:24:11:49:14:SJ cbx_util_mgl 2008:11:21:14:58:47:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = M4K 8 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  ROMifetch_altsyncram
	( 
	address_a,
	clock0,
	q_a) /* synthesis synthesis_clearbox=1 */;
	input   [9:0]  address_a;
	input   clock0;
	output   [31:0]  q_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block1a_0portadataout;
	wire  [0:0]   wire_ram_block1a_1portadataout;
	wire  [0:0]   wire_ram_block1a_2portadataout;
	wire  [0:0]   wire_ram_block1a_3portadataout;
	wire  [0:0]   wire_ram_block1a_4portadataout;
	wire  [0:0]   wire_ram_block1a_5portadataout;
	wire  [0:0]   wire_ram_block1a_6portadataout;
	wire  [0:0]   wire_ram_block1a_7portadataout;
	wire  [0:0]   wire_ram_block1a_8portadataout;
	wire  [0:0]   wire_ram_block1a_9portadataout;
	wire  [0:0]   wire_ram_block1a_10portadataout;
	wire  [0:0]   wire_ram_block1a_11portadataout;
	wire  [0:0]   wire_ram_block1a_12portadataout;
	wire  [0:0]   wire_ram_block1a_13portadataout;
	wire  [0:0]   wire_ram_block1a_14portadataout;
	wire  [0:0]   wire_ram_block1a_15portadataout;
	wire  [0:0]   wire_ram_block1a_16portadataout;
	wire  [0:0]   wire_ram_block1a_17portadataout;
	wire  [0:0]   wire_ram_block1a_18portadataout;
	wire  [0:0]   wire_ram_block1a_19portadataout;
	wire  [0:0]   wire_ram_block1a_20portadataout;
	wire  [0:0]   wire_ram_block1a_21portadataout;
	wire  [0:0]   wire_ram_block1a_22portadataout;
	wire  [0:0]   wire_ram_block1a_23portadataout;
	wire  [0:0]   wire_ram_block1a_24portadataout;
	wire  [0:0]   wire_ram_block1a_25portadataout;
	wire  [0:0]   wire_ram_block1a_26portadataout;
	wire  [0:0]   wire_ram_block1a_27portadataout;
	wire  [0:0]   wire_ram_block1a_28portadataout;
	wire  [0:0]   wire_ram_block1a_29portadataout;
	wire  [0:0]   wire_ram_block1a_30portadataout;
	wire  [0:0]   wire_ram_block1a_31portadataout;
	wire  [9:0]  address_a_wire;

	cycloneii_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_0portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.init_file = "all_prog_instructions.mif",
		ram_block1a_0.init_file_layout = "port_a",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111100100000000011000101,
		ram_block1a_0.operation_mode = "rom",
		ram_block1a_0.port_a_address_width = 10,
		ram_block1a_0.port_a_data_out_clear = "none",
		ram_block1a_0.port_a_data_out_clock = "none",
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_0.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 1023,
		ram_block1a_0.port_a_logical_ram_depth = 1024,
		ram_block1a_0.port_a_logical_ram_width = 32,
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_1portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.init_file = "all_prog_instructions.mif",
		ram_block1a_1.init_file_layout = "port_a",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100100000000110001000000000,
		ram_block1a_1.operation_mode = "rom",
		ram_block1a_1.port_a_address_width = 10,
		ram_block1a_1.port_a_data_out_clear = "none",
		ram_block1a_1.port_a_data_out_clock = "none",
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_1.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 1023,
		ram_block1a_1.port_a_logical_ram_depth = 1024,
		ram_block1a_1.port_a_logical_ram_width = 32,
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_2portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.init_file = "all_prog_instructions.mif",
		ram_block1a_2.init_file_layout = "port_a",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100111100101010011000000,
		ram_block1a_2.operation_mode = "rom",
		ram_block1a_2.port_a_address_width = 10,
		ram_block1a_2.port_a_data_out_clear = "none",
		ram_block1a_2.port_a_data_out_clock = "none",
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_2.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 1023,
		ram_block1a_2.port_a_logical_ram_depth = 1024,
		ram_block1a_2.port_a_logical_ram_width = 32,
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_3portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.init_file = "all_prog_instructions.mif",
		ram_block1a_3.init_file_layout = "port_a",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101110110000011100000000000,
		ram_block1a_3.operation_mode = "rom",
		ram_block1a_3.port_a_address_width = 10,
		ram_block1a_3.port_a_data_out_clear = "none",
		ram_block1a_3.port_a_data_out_clock = "none",
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_3.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_3.port_a_first_address = 0,
		ram_block1a_3.port_a_first_bit_number = 3,
		ram_block1a_3.port_a_last_address = 1023,
		ram_block1a_3.port_a_logical_ram_depth = 1024,
		ram_block1a_3.port_a_logical_ram_width = 32,
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_4portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.init_file = "all_prog_instructions.mif",
		ram_block1a_4.init_file_layout = "port_a",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101110010000001000000001000,
		ram_block1a_4.operation_mode = "rom",
		ram_block1a_4.port_a_address_width = 10,
		ram_block1a_4.port_a_data_out_clear = "none",
		ram_block1a_4.port_a_data_out_clock = "none",
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_4.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_4.port_a_first_address = 0,
		ram_block1a_4.port_a_first_bit_number = 4,
		ram_block1a_4.port_a_last_address = 1023,
		ram_block1a_4.port_a_logical_ram_depth = 1024,
		ram_block1a_4.port_a_logical_ram_width = 32,
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_5portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.init_file = "all_prog_instructions.mif",
		ram_block1a_5.init_file_layout = "port_a",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000011000011001000,
		ram_block1a_5.operation_mode = "rom",
		ram_block1a_5.port_a_address_width = 10,
		ram_block1a_5.port_a_data_out_clear = "none",
		ram_block1a_5.port_a_data_out_clock = "none",
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_5.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_5.port_a_first_address = 0,
		ram_block1a_5.port_a_first_bit_number = 5,
		ram_block1a_5.port_a_last_address = 1023,
		ram_block1a_5.port_a_logical_ram_depth = 1024,
		ram_block1a_5.port_a_logical_ram_width = 32,
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_6portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.init_file = "all_prog_instructions.mif",
		ram_block1a_6.init_file_layout = "port_a",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000000001000,
		ram_block1a_6.operation_mode = "rom",
		ram_block1a_6.port_a_address_width = 10,
		ram_block1a_6.port_a_data_out_clear = "none",
		ram_block1a_6.port_a_data_out_clock = "none",
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_6.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_6.port_a_first_address = 0,
		ram_block1a_6.port_a_first_bit_number = 6,
		ram_block1a_6.port_a_last_address = 1023,
		ram_block1a_6.port_a_logical_ram_depth = 1024,
		ram_block1a_6.port_a_logical_ram_width = 32,
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_7portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.init_file = "all_prog_instructions.mif",
		ram_block1a_7.init_file_layout = "port_a",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000000000000,
		ram_block1a_7.operation_mode = "rom",
		ram_block1a_7.port_a_address_width = 10,
		ram_block1a_7.port_a_data_out_clear = "none",
		ram_block1a_7.port_a_data_out_clock = "none",
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_7.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_7.port_a_first_address = 0,
		ram_block1a_7.port_a_first_bit_number = 7,
		ram_block1a_7.port_a_last_address = 1023,
		ram_block1a_7.port_a_logical_ram_depth = 1024,
		ram_block1a_7.port_a_logical_ram_width = 32,
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_8portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.init_file = "all_prog_instructions.mif",
		ram_block1a_8.init_file_layout = "port_a",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000000000000,
		ram_block1a_8.operation_mode = "rom",
		ram_block1a_8.port_a_address_width = 10,
		ram_block1a_8.port_a_data_out_clear = "none",
		ram_block1a_8.port_a_data_out_clock = "none",
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_8.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_8.port_a_first_address = 0,
		ram_block1a_8.port_a_first_bit_number = 8,
		ram_block1a_8.port_a_last_address = 1023,
		ram_block1a_8.port_a_logical_ram_depth = 1024,
		ram_block1a_8.port_a_logical_ram_width = 32,
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_9portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.init_file = "all_prog_instructions.mif",
		ram_block1a_9.init_file_layout = "port_a",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000000000000,
		ram_block1a_9.operation_mode = "rom",
		ram_block1a_9.port_a_address_width = 10,
		ram_block1a_9.port_a_data_out_clear = "none",
		ram_block1a_9.port_a_data_out_clock = "none",
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_9.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_9.port_a_first_address = 0,
		ram_block1a_9.port_a_first_bit_number = 9,
		ram_block1a_9.port_a_last_address = 1023,
		ram_block1a_9.port_a_logical_ram_depth = 1024,
		ram_block1a_9.port_a_logical_ram_width = 32,
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_10portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.init_file = "all_prog_instructions.mif",
		ram_block1a_10.init_file_layout = "port_a",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000000000000,
		ram_block1a_10.operation_mode = "rom",
		ram_block1a_10.port_a_address_width = 10,
		ram_block1a_10.port_a_data_out_clear = "none",
		ram_block1a_10.port_a_data_out_clock = "none",
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_10.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_10.port_a_first_address = 0,
		ram_block1a_10.port_a_first_bit_number = 10,
		ram_block1a_10.port_a_last_address = 1023,
		ram_block1a_10.port_a_logical_ram_depth = 1024,
		ram_block1a_10.port_a_logical_ram_width = 32,
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_11portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.init_file = "all_prog_instructions.mif",
		ram_block1a_11.init_file_layout = "port_a",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000011000001000000,
		ram_block1a_11.operation_mode = "rom",
		ram_block1a_11.port_a_address_width = 10,
		ram_block1a_11.port_a_data_out_clear = "none",
		ram_block1a_11.port_a_data_out_clock = "none",
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_11.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_11.port_a_first_address = 0,
		ram_block1a_11.port_a_first_bit_number = 11,
		ram_block1a_11.port_a_last_address = 1023,
		ram_block1a_11.port_a_logical_ram_depth = 1024,
		ram_block1a_11.port_a_logical_ram_width = 32,
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_12
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_12portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_12.connectivity_checking = "OFF",
		ram_block1a_12.init_file = "all_prog_instructions.mif",
		ram_block1a_12.init_file_layout = "port_a",
		ram_block1a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_12.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000010000101,
		ram_block1a_12.operation_mode = "rom",
		ram_block1a_12.port_a_address_width = 10,
		ram_block1a_12.port_a_data_out_clear = "none",
		ram_block1a_12.port_a_data_out_clock = "none",
		ram_block1a_12.port_a_data_width = 1,
		ram_block1a_12.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_12.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_12.port_a_first_address = 0,
		ram_block1a_12.port_a_first_bit_number = 12,
		ram_block1a_12.port_a_last_address = 1023,
		ram_block1a_12.port_a_logical_ram_depth = 1024,
		ram_block1a_12.port_a_logical_ram_width = 32,
		ram_block1a_12.ram_block_type = "AUTO",
		ram_block1a_12.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_13
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_13portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_13.connectivity_checking = "OFF",
		ram_block1a_13.init_file = "all_prog_instructions.mif",
		ram_block1a_13.init_file_layout = "port_a",
		ram_block1a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_13.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000000000000,
		ram_block1a_13.operation_mode = "rom",
		ram_block1a_13.port_a_address_width = 10,
		ram_block1a_13.port_a_data_out_clear = "none",
		ram_block1a_13.port_a_data_out_clock = "none",
		ram_block1a_13.port_a_data_width = 1,
		ram_block1a_13.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_13.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_13.port_a_first_address = 0,
		ram_block1a_13.port_a_first_bit_number = 13,
		ram_block1a_13.port_a_last_address = 1023,
		ram_block1a_13.port_a_logical_ram_depth = 1024,
		ram_block1a_13.port_a_logical_ram_width = 32,
		ram_block1a_13.ram_block_type = "AUTO",
		ram_block1a_13.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_14
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_14portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_14.connectivity_checking = "OFF",
		ram_block1a_14.init_file = "all_prog_instructions.mif",
		ram_block1a_14.init_file_layout = "port_a",
		ram_block1a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_14.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000011000000,
		ram_block1a_14.operation_mode = "rom",
		ram_block1a_14.port_a_address_width = 10,
		ram_block1a_14.port_a_data_out_clear = "none",
		ram_block1a_14.port_a_data_out_clock = "none",
		ram_block1a_14.port_a_data_width = 1,
		ram_block1a_14.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_14.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_14.port_a_first_address = 0,
		ram_block1a_14.port_a_first_bit_number = 14,
		ram_block1a_14.port_a_last_address = 1023,
		ram_block1a_14.port_a_logical_ram_depth = 1024,
		ram_block1a_14.port_a_logical_ram_width = 32,
		ram_block1a_14.ram_block_type = "AUTO",
		ram_block1a_14.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_15
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_15portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_15.connectivity_checking = "OFF",
		ram_block1a_15.init_file = "all_prog_instructions.mif",
		ram_block1a_15.init_file_layout = "port_a",
		ram_block1a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_15.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100010000001000000000000,
		ram_block1a_15.operation_mode = "rom",
		ram_block1a_15.port_a_address_width = 10,
		ram_block1a_15.port_a_data_out_clear = "none",
		ram_block1a_15.port_a_data_out_clock = "none",
		ram_block1a_15.port_a_data_width = 1,
		ram_block1a_15.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_15.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_15.port_a_first_address = 0,
		ram_block1a_15.port_a_first_bit_number = 15,
		ram_block1a_15.port_a_last_address = 1023,
		ram_block1a_15.port_a_logical_ram_depth = 1024,
		ram_block1a_15.port_a_logical_ram_width = 32,
		ram_block1a_15.ram_block_type = "AUTO",
		ram_block1a_15.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_16
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_16portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_16.connectivity_checking = "OFF",
		ram_block1a_16.init_file = "all_prog_instructions.mif",
		ram_block1a_16.init_file_layout = "port_a",
		ram_block1a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_16.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101001001010000100010111,
		ram_block1a_16.operation_mode = "rom",
		ram_block1a_16.port_a_address_width = 10,
		ram_block1a_16.port_a_data_out_clear = "none",
		ram_block1a_16.port_a_data_out_clock = "none",
		ram_block1a_16.port_a_data_width = 1,
		ram_block1a_16.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_16.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_16.port_a_first_address = 0,
		ram_block1a_16.port_a_first_bit_number = 16,
		ram_block1a_16.port_a_last_address = 1023,
		ram_block1a_16.port_a_logical_ram_depth = 1024,
		ram_block1a_16.port_a_logical_ram_width = 32,
		ram_block1a_16.ram_block_type = "AUTO",
		ram_block1a_16.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_17
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_17portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_17.connectivity_checking = "OFF",
		ram_block1a_17.init_file = "all_prog_instructions.mif",
		ram_block1a_17.init_file_layout = "port_a",
		ram_block1a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_17.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000010001001010100101000,
		ram_block1a_17.operation_mode = "rom",
		ram_block1a_17.port_a_address_width = 10,
		ram_block1a_17.port_a_data_out_clear = "none",
		ram_block1a_17.port_a_data_out_clock = "none",
		ram_block1a_17.port_a_data_width = 1,
		ram_block1a_17.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_17.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_17.port_a_first_address = 0,
		ram_block1a_17.port_a_first_bit_number = 17,
		ram_block1a_17.port_a_last_address = 1023,
		ram_block1a_17.port_a_logical_ram_depth = 1024,
		ram_block1a_17.port_a_logical_ram_width = 32,
		ram_block1a_17.ram_block_type = "AUTO",
		ram_block1a_17.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_18
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_18portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_18.connectivity_checking = "OFF",
		ram_block1a_18.init_file = "all_prog_instructions.mif",
		ram_block1a_18.init_file_layout = "port_a",
		ram_block1a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_18.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000110000000000001010,
		ram_block1a_18.operation_mode = "rom",
		ram_block1a_18.port_a_address_width = 10,
		ram_block1a_18.port_a_data_out_clear = "none",
		ram_block1a_18.port_a_data_out_clock = "none",
		ram_block1a_18.port_a_data_width = 1,
		ram_block1a_18.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_18.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_18.port_a_first_address = 0,
		ram_block1a_18.port_a_first_bit_number = 18,
		ram_block1a_18.port_a_last_address = 1023,
		ram_block1a_18.port_a_logical_ram_depth = 1024,
		ram_block1a_18.port_a_logical_ram_width = 32,
		ram_block1a_18.ram_block_type = "AUTO",
		ram_block1a_18.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_19
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_19portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_19.connectivity_checking = "OFF",
		ram_block1a_19.init_file = "all_prog_instructions.mif",
		ram_block1a_19.init_file_layout = "port_a",
		ram_block1a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_19.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111011010100000000,
		ram_block1a_19.operation_mode = "rom",
		ram_block1a_19.port_a_address_width = 10,
		ram_block1a_19.port_a_data_out_clear = "none",
		ram_block1a_19.port_a_data_out_clock = "none",
		ram_block1a_19.port_a_data_width = 1,
		ram_block1a_19.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_19.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_19.port_a_first_address = 0,
		ram_block1a_19.port_a_first_bit_number = 19,
		ram_block1a_19.port_a_last_address = 1023,
		ram_block1a_19.port_a_logical_ram_depth = 1024,
		ram_block1a_19.port_a_logical_ram_width = 32,
		ram_block1a_19.ram_block_type = "AUTO",
		ram_block1a_19.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_20
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_20portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_20.connectivity_checking = "OFF",
		ram_block1a_20.init_file = "all_prog_instructions.mif",
		ram_block1a_20.init_file_layout = "port_a",
		ram_block1a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_20.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111111100000000100000110000,
		ram_block1a_20.operation_mode = "rom",
		ram_block1a_20.port_a_address_width = 10,
		ram_block1a_20.port_a_data_out_clear = "none",
		ram_block1a_20.port_a_data_out_clock = "none",
		ram_block1a_20.port_a_data_width = 1,
		ram_block1a_20.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_20.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_20.port_a_first_address = 0,
		ram_block1a_20.port_a_first_bit_number = 20,
		ram_block1a_20.port_a_last_address = 1023,
		ram_block1a_20.port_a_logical_ram_depth = 1024,
		ram_block1a_20.port_a_logical_ram_width = 32,
		ram_block1a_20.ram_block_type = "AUTO",
		ram_block1a_20.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_21
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_21portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_21.connectivity_checking = "OFF",
		ram_block1a_21.init_file = "all_prog_instructions.mif",
		ram_block1a_21.init_file_layout = "port_a",
		ram_block1a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_21.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001101100001011001010,
		ram_block1a_21.operation_mode = "rom",
		ram_block1a_21.port_a_address_width = 10,
		ram_block1a_21.port_a_data_out_clear = "none",
		ram_block1a_21.port_a_data_out_clock = "none",
		ram_block1a_21.port_a_data_width = 1,
		ram_block1a_21.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_21.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_21.port_a_first_address = 0,
		ram_block1a_21.port_a_first_bit_number = 21,
		ram_block1a_21.port_a_last_address = 1023,
		ram_block1a_21.port_a_logical_ram_depth = 1024,
		ram_block1a_21.port_a_logical_ram_width = 32,
		ram_block1a_21.ram_block_type = "AUTO",
		ram_block1a_21.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_22
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_22portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_22.connectivity_checking = "OFF",
		ram_block1a_22.init_file = "all_prog_instructions.mif",
		ram_block1a_22.init_file_layout = "port_a",
		ram_block1a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_22.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010110011011100000000,
		ram_block1a_22.operation_mode = "rom",
		ram_block1a_22.port_a_address_width = 10,
		ram_block1a_22.port_a_data_out_clear = "none",
		ram_block1a_22.port_a_data_out_clock = "none",
		ram_block1a_22.port_a_data_width = 1,
		ram_block1a_22.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_22.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_22.port_a_first_address = 0,
		ram_block1a_22.port_a_first_bit_number = 22,
		ram_block1a_22.port_a_last_address = 1023,
		ram_block1a_22.port_a_logical_ram_depth = 1024,
		ram_block1a_22.port_a_logical_ram_width = 32,
		ram_block1a_22.ram_block_type = "AUTO",
		ram_block1a_22.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_23
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_23portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_23.connectivity_checking = "OFF",
		ram_block1a_23.init_file = "all_prog_instructions.mif",
		ram_block1a_23.init_file_layout = "port_a",
		ram_block1a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_23.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000,
		ram_block1a_23.operation_mode = "rom",
		ram_block1a_23.port_a_address_width = 10,
		ram_block1a_23.port_a_data_out_clear = "none",
		ram_block1a_23.port_a_data_out_clock = "none",
		ram_block1a_23.port_a_data_width = 1,
		ram_block1a_23.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_23.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_23.port_a_first_address = 0,
		ram_block1a_23.port_a_first_bit_number = 23,
		ram_block1a_23.port_a_last_address = 1023,
		ram_block1a_23.port_a_logical_ram_depth = 1024,
		ram_block1a_23.port_a_logical_ram_width = 32,
		ram_block1a_23.ram_block_type = "AUTO",
		ram_block1a_23.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_24
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_24portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_24.connectivity_checking = "OFF",
		ram_block1a_24.init_file = "all_prog_instructions.mif",
		ram_block1a_24.init_file_layout = "port_a",
		ram_block1a_24.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_24.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111011011110000000,
		ram_block1a_24.operation_mode = "rom",
		ram_block1a_24.port_a_address_width = 10,
		ram_block1a_24.port_a_data_out_clear = "none",
		ram_block1a_24.port_a_data_out_clock = "none",
		ram_block1a_24.port_a_data_width = 1,
		ram_block1a_24.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_24.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_24.port_a_first_address = 0,
		ram_block1a_24.port_a_first_bit_number = 24,
		ram_block1a_24.port_a_last_address = 1023,
		ram_block1a_24.port_a_logical_ram_depth = 1024,
		ram_block1a_24.port_a_logical_ram_width = 32,
		ram_block1a_24.ram_block_type = "AUTO",
		ram_block1a_24.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_25
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_25portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_25.connectivity_checking = "OFF",
		ram_block1a_25.init_file = "all_prog_instructions.mif",
		ram_block1a_25.init_file_layout = "port_a",
		ram_block1a_25.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_25.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_25.operation_mode = "rom",
		ram_block1a_25.port_a_address_width = 10,
		ram_block1a_25.port_a_data_out_clear = "none",
		ram_block1a_25.port_a_data_out_clock = "none",
		ram_block1a_25.port_a_data_width = 1,
		ram_block1a_25.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_25.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_25.port_a_first_address = 0,
		ram_block1a_25.port_a_first_bit_number = 25,
		ram_block1a_25.port_a_last_address = 1023,
		ram_block1a_25.port_a_logical_ram_depth = 1024,
		ram_block1a_25.port_a_logical_ram_width = 32,
		ram_block1a_25.ram_block_type = "AUTO",
		ram_block1a_25.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_26
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_26portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_26.connectivity_checking = "OFF",
		ram_block1a_26.init_file = "all_prog_instructions.mif",
		ram_block1a_26.init_file_layout = "port_a",
		ram_block1a_26.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_26.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111100000100001111,
		ram_block1a_26.operation_mode = "rom",
		ram_block1a_26.port_a_address_width = 10,
		ram_block1a_26.port_a_data_out_clear = "none",
		ram_block1a_26.port_a_data_out_clock = "none",
		ram_block1a_26.port_a_data_width = 1,
		ram_block1a_26.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_26.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_26.port_a_first_address = 0,
		ram_block1a_26.port_a_first_bit_number = 26,
		ram_block1a_26.port_a_last_address = 1023,
		ram_block1a_26.port_a_logical_ram_depth = 1024,
		ram_block1a_26.port_a_logical_ram_width = 32,
		ram_block1a_26.ram_block_type = "AUTO",
		ram_block1a_26.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_27
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_27portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_27.connectivity_checking = "OFF",
		ram_block1a_27.init_file = "all_prog_instructions.mif",
		ram_block1a_27.init_file_layout = "port_a",
		ram_block1a_27.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_27.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101010100011000100100000101,
		ram_block1a_27.operation_mode = "rom",
		ram_block1a_27.port_a_address_width = 10,
		ram_block1a_27.port_a_data_out_clear = "none",
		ram_block1a_27.port_a_data_out_clock = "none",
		ram_block1a_27.port_a_data_width = 1,
		ram_block1a_27.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_27.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_27.port_a_first_address = 0,
		ram_block1a_27.port_a_first_bit_number = 27,
		ram_block1a_27.port_a_last_address = 1023,
		ram_block1a_27.port_a_logical_ram_depth = 1024,
		ram_block1a_27.port_a_logical_ram_width = 32,
		ram_block1a_27.ram_block_type = "AUTO",
		ram_block1a_27.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_28
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_28portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_28.connectivity_checking = "OFF",
		ram_block1a_28.init_file = "all_prog_instructions.mif",
		ram_block1a_28.init_file_layout = "port_a",
		ram_block1a_28.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_28.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100100001000001111,
		ram_block1a_28.operation_mode = "rom",
		ram_block1a_28.port_a_address_width = 10,
		ram_block1a_28.port_a_data_out_clear = "none",
		ram_block1a_28.port_a_data_out_clock = "none",
		ram_block1a_28.port_a_data_width = 1,
		ram_block1a_28.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_28.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_28.port_a_first_address = 0,
		ram_block1a_28.port_a_first_bit_number = 28,
		ram_block1a_28.port_a_last_address = 1023,
		ram_block1a_28.port_a_logical_ram_depth = 1024,
		ram_block1a_28.port_a_logical_ram_width = 32,
		ram_block1a_28.ram_block_type = "AUTO",
		ram_block1a_28.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_29
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_29portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_29.connectivity_checking = "OFF",
		ram_block1a_29.init_file = "all_prog_instructions.mif",
		ram_block1a_29.init_file_layout = "port_a",
		ram_block1a_29.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_29.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010101011000001010000111111,
		ram_block1a_29.operation_mode = "rom",
		ram_block1a_29.port_a_address_width = 10,
		ram_block1a_29.port_a_data_out_clear = "none",
		ram_block1a_29.port_a_data_out_clock = "none",
		ram_block1a_29.port_a_data_width = 1,
		ram_block1a_29.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_29.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_29.port_a_first_address = 0,
		ram_block1a_29.port_a_first_bit_number = 29,
		ram_block1a_29.port_a_last_address = 1023,
		ram_block1a_29.port_a_logical_ram_depth = 1024,
		ram_block1a_29.port_a_logical_ram_width = 32,
		ram_block1a_29.ram_block_type = "AUTO",
		ram_block1a_29.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_30
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_30portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_30.connectivity_checking = "OFF",
		ram_block1a_30.init_file = "all_prog_instructions.mif",
		ram_block1a_30.init_file_layout = "port_a",
		ram_block1a_30.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_30.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_30.operation_mode = "rom",
		ram_block1a_30.port_a_address_width = 10,
		ram_block1a_30.port_a_data_out_clear = "none",
		ram_block1a_30.port_a_data_out_clock = "none",
		ram_block1a_30.port_a_data_width = 1,
		ram_block1a_30.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_30.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_30.port_a_first_address = 0,
		ram_block1a_30.port_a_first_bit_number = 30,
		ram_block1a_30.port_a_last_address = 1023,
		ram_block1a_30.port_a_logical_ram_depth = 1024,
		ram_block1a_30.port_a_logical_ram_width = 32,
		ram_block1a_30.ram_block_type = "AUTO",
		ram_block1a_30.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_31
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_31portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_31.connectivity_checking = "OFF",
		ram_block1a_31.init_file = "all_prog_instructions.mif",
		ram_block1a_31.init_file_layout = "port_a",
		ram_block1a_31.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_31.mem_init0 = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011000000100000000,
		ram_block1a_31.operation_mode = "rom",
		ram_block1a_31.port_a_address_width = 10,
		ram_block1a_31.port_a_data_out_clear = "none",
		ram_block1a_31.port_a_data_out_clock = "none",
		ram_block1a_31.port_a_data_width = 1,
		ram_block1a_31.port_a_disable_ce_on_input_registers = "on",
		ram_block1a_31.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_31.port_a_first_address = 0,
		ram_block1a_31.port_a_first_bit_number = 31,
		ram_block1a_31.port_a_last_address = 1023,
		ram_block1a_31.port_a_logical_ram_depth = 1024,
		ram_block1a_31.port_a_logical_ram_width = 32,
		ram_block1a_31.ram_block_type = "AUTO",
		ram_block1a_31.lpm_type = "cycloneii_ram_block";
	assign
		address_a_wire = address_a,
		q_a = {wire_ram_block1a_31portadataout[0], wire_ram_block1a_30portadataout[0], wire_ram_block1a_29portadataout[0], wire_ram_block1a_28portadataout[0], wire_ram_block1a_27portadataout[0], wire_ram_block1a_26portadataout[0], wire_ram_block1a_25portadataout[0], wire_ram_block1a_24portadataout[0], wire_ram_block1a_23portadataout[0], wire_ram_block1a_22portadataout[0], wire_ram_block1a_21portadataout[0], wire_ram_block1a_20portadataout[0], wire_ram_block1a_19portadataout[0], wire_ram_block1a_18portadataout[0], wire_ram_block1a_17portadataout[0], wire_ram_block1a_16portadataout[0], wire_ram_block1a_15portadataout[0], wire_ram_block1a_14portadataout[0], wire_ram_block1a_13portadataout[0], wire_ram_block1a_12portadataout[0], wire_ram_block1a_11portadataout[0], wire_ram_block1a_10portadataout[0], wire_ram_block1a_9portadataout[0], wire_ram_block1a_8portadataout[0], wire_ram_block1a_7portadataout[0], wire_ram_block1a_6portadataout[0], wire_ram_block1a_5portadataout[0], wire_ram_block1a_4portadataout[0], wire_ram_block1a_3portadataout[0], wire_ram_block1a_2portadataout[0], wire_ram_block1a_1portadataout[0], wire_ram_block1a_0portadataout[0]};
	initial/*synthesis enable_verilog_initial_construct*/
 	begin
		$display("Warning: Memory initialization file all_prog_instructions.mif is not of the dimensions 1024 X 32, the resulting memory design may not produce consistent simulation results.");
	end
endmodule //ROMifetch_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module ROMifetch (
	address,
	clock,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[9:0]  address;
	input	  clock;
	output	[31:0]  q;

	wire [31:0] sub_wire0;
	wire [31:0] q = sub_wire0[31:0];

	ROMifetch_altsyncram	ROMifetch_altsyncram_component (
				.clock0 (clock),
				.address_a (address),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "all_prog_instructions.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "1024"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "10"
// Retrieval info: PRIVATE: WidthData NUMERIC "32"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "all_prog_instructions.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=NO"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "1024"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "ROM"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "UNREGISTERED"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "10"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "32"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 10 0 INPUT NODEFVAL address[9..0]
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL clock
// Retrieval info: USED_PORT: q 0 0 32 0 OUTPUT NODEFVAL q[31..0]
// Retrieval info: CONNECT: @address_a 0 0 10 0 address 0 0 10 0
// Retrieval info: CONNECT: q 0 0 32 0 @q_a 0 0 32 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: GEN_FILE: TYPE_NORMAL ROMifetch.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ROMifetch.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ROMifetch.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ROMifetch.bsf TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ROMifetch_inst.vhd FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ROMifetch_waveforms.html TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL ROMifetch_wave*.jpg FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL ROMifetch_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
